In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Location hierarchy.csv")

In [3]:
df

,State ID,State Name,State Name (Hindi),Division ID,Division Name,Division Name (Hindi),District Name,District ID,District Name (Hindi),Block ID,Block Name,Block Name (Hindi),Present in IMD Agromet
0,1,Andhra Pradesh,आंध्र प्रदेश,195,Zone 1,क्षेत्र १,Srikakulam,101.0,श्रीकाकुलम,684,Amadalavalasa,अमुदलवलासा,True
1,1,Andhra Pradesh,आंध्र प्रदेश,195,Zone 1,क्षेत्र १,Srikakulam,101.0,श्रीकाकुलम,685,Bhamini,भामिनी,True
2,1,Andhra Pradesh,आंध्र प्रदेश,195,Zone 1,क्षेत्र १,Srikakulam,101.0,श्रीकाकुलम,686,Burja,बुर्ज,True
3,1,Andhra Pradesh,आंध्र प्रदेश,195,Zone 1,क्षेत्र १,Srikakulam,101.0,श्रीकाकुलम,687,Etcherla,Etcherla,True
4,1,Andhra Pradesh,आंध्र प्रदेश,195,Zone 1,क्षेत्र १,Srikakulam,101.0,श्रीकाकुलम,688,Ganguvarisigadam,गंगुवरिसिगदम,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5289,21,West Bengal,पश्चिम बंगाल,311,Presidency,अध्यक्षता,South 24 Parganas,2109.0,दक्षिण चौबीस परगना,5973,Namkhana,नामखाना,True
5290,21,West Bengal,पश्चिम बंगाल,311,Presidency,अध्यक्षता,South 24 Parganas,2109.0,दक्षिण चौबीस परगना,5974,Patharpratima,पाथरप्रतिमा,True
5291,21,West Bengal,पश्चिम बंगाल,311,Presidency,अध्यक्षता,South 24 Parganas,2109.0,दक्षिण चौबीस परगना,5975,Sagar,सागर,True
5292,21,West Bengal,पश्चिम बंगाल,311,Presidency,अध्यक्षता,South 24 Parganas,2109.0,दक्षिण चौबीस परगना,5976,Sonarpur,सोनारपुर,True
5293,21,West Bengal,पश्चिम बंगाल,311,Presidency,अध्यक्षता,South 24 Parganas,2109.0,दक्षिण चौबीस परगना,5977,Thakurpukur Mahestola,ठाकुरपुकुर महेस्तोला,True

In [4]:
df.drop(['State Name (Hindi)','Division Name (Hindi)','District Name (Hindi)','Block Name (Hindi)'],axis=1,inplace=True)

In [5]:
df["Present in IMD Agromet"].unique()

array([True, False, nan], dtype=object)

In [6]:
df_final=df.loc[df["Present in IMD Agromet"]==True]

In [7]:
df_final

,State ID,State Name,Division ID,Division Name,District Name,District ID,Block ID,Block Name,Present in IMD Agromet
0,1,Andhra Pradesh,195,Zone 1,Srikakulam,101.0,684,Amadalavalasa,True
1,1,Andhra Pradesh,195,Zone 1,Srikakulam,101.0,685,Bhamini,True
2,1,Andhra Pradesh,195,Zone 1,Srikakulam,101.0,686,Burja,True
3,1,Andhra Pradesh,195,Zone 1,Srikakulam,101.0,687,Etcherla,True
4,1,Andhra Pradesh,195,Zone 1,Srikakulam,101.0,688,Ganguvarisigadam,True
...,...,...,...,...,...,...,...,...,...
5289,21,West Bengal,311,Presidency,South 24 Parganas,2109.0,5973,Namkhana,True
5290,21,West Bengal,311,Presidency,South 24 Parganas,2109.0,5974,Patharpratima,True
5291,21,West Bengal,311,Presidency,South 24 Parganas,2109.0,5975,Sagar,True
5292,21,West Bengal,311,Presidency,South 24 Parganas,2109.0,5976,Sonarpur,True
5293,21,West Bengal,311,Presidency,South 24 Parganas,2109.0,5977,Thakurpukur Mahestola,True

In [9]:
df_final["Present in IMD Agromet"].unique()

array([True], dtype=object)

In [12]:
df_final.to_csv("IMD-Agromet_registered_locations.csv",index=False)